<?php



namespace SpExpress\Sdk\Enums;

final class ErrorCodes
{
    public const ERROR_OPTIONS_ADDITIONS_INVALID_FORMAT = 1411;

    public const ERROR_SYSTEM_MAINTENANCE = 1000;

    public const ERROR_PACKAGE_PICKUP_NOT_POSSIBLE = 1470;

    public const ERROR_OPTIONS_COD_BANK_ACCOUNT_STRING_REQUIRED = 1423;

    public const ERROR_OPTIONS_ADDITION_NOT_AVAILABLE = 1410;

    public const ERROR_POINT_NOT_FOUND = 6001;

    public const ERROR_SENDER_UNKNOWN_COUNTRY = 1302;

    public const ERROR_RETURN_NOT_POSSIBLE_FOR_THIS_PACKAGE = 1481;

    public const ERROR_RETURN_ALREADY_CREATED_FOR_THIS_PACKAGE = 1482;

    public const ERROR_ID_INVALID_FORMAT = 4000;

    public const ERROR_ACCOUNT_SETTINGS_SERVICE_NOT_AVAILABLE = 1010;

    public const ERROR_RETURN_NOT_POSSIBLE_FOR_MULTIPACKAGES = 1480;

    public const ERROR_PACKAGE_TOO_HEAVY = 1110;

    public const ERROR_PROCESSING_PROBLEMS = 1053;

    public const ERROR_OPTIONS_COD_NOT_AVAILABLE_FOR_THIS_OPERATOR = 1426;

    public const ERROR_OPTIONS_INVALID_OPERATOR = 1450;

    public const ERROR_OPTIONS_COD_AVAILABLE_ONLY_ON_PL_PL_ROUTE = 1422;

    public const ERROR_OPTIONS_COD_INVALID_FORMAT = 1420;

    public const ERROR_COULD_NOT_RETRIEVE_LABEL = 4001;

    public const ERROR_AUTHENTICATION_PROBLEMS = 1001;

    public const ERROR_PACKAGE_CARRIAGE_NOT_POSSIBLE = 1471;

    public const ERROR_OPTIONS_INVALID_PRINT_SERVER = 1415;

    public const ERROR_PACKAGE_NOT_FOUND_OR_YOU_ARE_NOT_THE_OWNER = 3004;

    public const ERROR_ITEM_INVALID = 3005;

    public const ERROR_RECEIVER_INVALID_DATA = 1300;

    public const ERROR_POINT_INVALID_DATA = 6002;

    public const ERROR_OPTIONS_COD_INVALID_BANK_ACCOUNT = 1425;

    public const ERROR_OPTIONS_INVALID_DATA = 1400;

    public const ERROR_CUSTOMS_DUTY_INVALID_DATA = 1500;

    public const ERROR_OPTIONS_COD_TOO_MUCH = 1421;

    public const ERROR_RECEIVER_UNKNOWN_PARAMETER = 1201;

    public const ERROR_ALREADY_CANCELLED = 5001;

    public const ERROR_OPTIONS_PICKUP_MODE_DISABLED = 1413;

    public const ERROR_RECEIVER_UNKNOWN_COUNTRY = 1202;

    public const ERROR_COULD_NOT_CANCEL = 5000;

    public const ERROR_PACKAGE_INVALID_DATA = 1100;

    public const ERROR_ACCOUNT_LOCKED = 1002;

    public const ERROR_OPTIONS_TOO_MANY_PACKAGES = 1460;

    public const ERROR_PACKAGES_NO_DATA = 3001;

    public const ERROR_EXCEPTION_1 = 1051;

    public const ERROR_EXCEPTION_2 = 1052;

    public const ERROR_SENDER_INVALID_DATA = 1200;

    public const ERROR_IDS_INVALID_FORMAT = 3000;

    public const ERROR_PACKAGES_TOO_MANY = 3002;

    public const ERROR_PACKAGE_TOO_BIG = 1111;

    public const ERROR_UNKNOWN_PROVIDER = 6000;

    public const ERROR_OPTIONS_INVALID_PICKUP_MODE = 1412;

    public const ERROR_SENDER_UNKNOWN_PARAMETER = 1301;

    public const ERROR_OPTIONS_INVALID_LABEL_TYPE = 1416;

    public const ERROR_OPTIONS_COD_INCORRECT_CURRENCY = 1427;

    public const ERROR_OPTIONS_UNKNOWN_PARAMETER = 1401;

    public const ERROR_OPTIONS_OPERATOR_NOT_AVAILABLE_FOR_YOU_CONTACT_US = 1452;

    public const ERROR_UNKNOWN_EXCEPTION = 1050;

    public const ERROR_OPTIONS_OPERATOR_NOT_AVAILABLE_FOR_THIS_COUNTRY = 1451;

    public const ERROR_OPTIONS_COD_INVALID_ACCOUNT_CURRENCY = 1424;

    public const ERROR_OPTIONS_INVALID_DELIVERY_POINT = 1420;

    public const ERROR_PACKAGE_UNKNOWN_PARAMETER = 1101;

    public const ERROR_COULD_NOT_UPDATE_WEIGHT = 6000;

    public const ERROR_PRINT_APP_ERROR = 7000;

    public const ERROR_DELIVERY_ADVICE_ERROR = 7100;
}
